#pragma once

#define PACKET_ACTION_HELLO 1

#define PACKET_ACTION_CONV_CREATE 50
#define PACKET_ACTION_CONV_SET_WEIGHTS 51
#define PACKET_ACTION_CONV_SET_BIASES 52
#define PACKET_ACTION_CONV_SET_ROLLING_MEAN 53
#define PACKET_ACTION_CONV_SET_ROLLING_VARIANCE 54
#define PACKET_ACTION_CONV_SET_SCALES 55
#define PACKET_ACTION_CONV_FORWARD 56

#define PACKET_ACTION_MAXP_CREATE 60

#define PACKET_ACTION_CONV_BLOCK_CREATE 70
#define PACKET_ACTION_CONV_BLOCK_FORWARD 71
